### ISSUE TITLE
Consultation of code diversion

### ISSUE THREAD

**Issue by PINTO0309** [kodamap/tellooo#1]
Hi, @kodamap san.

I am sorry to contact you suddenly. I contacted you, hoping to use your great repository for my hobby coding work. Are there any problems with modifying your program and posting it to Qiita or committing to the Github repository?

I think you are busy, but it helps if you can tell if there are restrictions.

Kind regards,
Katsuya Hyodo

**Comment by kodamap** [comment]
Hi, PINTO san. Thank you for your comment. Of course there is no problem. (sorry for my messy code ..)

**Comment by PINTO0309** [comment]
Thank you for your patience! When publishing to Github, I will list your account name as a collaborator!
