### ISSUE TITLE
Add API support to output image data 

### ISSUE THREAD

**Issue by nfkok** [kodamap/tellooo#3]
Hi, how can I get the real-time image data for example the coordinate data of the bounding box or color data to allow me to control movements depending on the size of the bounding box or the color of object?

**Comment by kodamap** [comment]
This app doesn't have an api to get image data for now. But you can get the size of the bounding box in the code below.

**tracking mode**

`track_window_area` is the size of the bounding box. (I use this for `forward` and `backward` movement.)


```py
# tracking.py
def _calc_track_area_ratio(self, track_window, track_area):
    track_area = track_area[0] * track_area[1]
    track_window_area = track_window[2] * track_window[3]
```

**object detection**

`startX, startY, endX, endY` is the coordinate data of the bounding box.

```py
# detectors.py(line:370)
(startX, startY, endX, endY) = box.astype("int")
```

You can calcurate the size of the bounding box.

```py
(endY-startY) * (endX-startX)
```

**face detection**

`xmin, ymin, xmax, ymax` is the coordinate data of the bounding box.

```py
# interactive_detection.py(line:231)
xmin, ymin, xmax, ymax = box.astype("int")
```

I know my answer isn't what you expect but I hope this helps.

**Comment by nfkok** [comment]
@kodamap Thanks. By referring to your script and using API provided by [damiafuentes](https://github.com/damiafuentes/DJITelloPy), I have implemented what I wanted.
