### ISSUE TITLE
Ubuntu?

### ISSUE THREAD

**Issue by anuchandra** [kodamap/tellooo#4]
Hi, have you considered what would be required for Ubuntu? I tried installing but I get the error:

'Please try to specify cpu extensions library path in demo's command line parameters using -l or --cpu_extension command line argument'

The binaries in extension.zip are for windows I think. I have installed openvino on my ubuntu machine and it works fine. Do you know what is specifically required to make tellooo work with ubuntu?

**Comment by anuchandra** [comment]
I got it working for Ubuntu. The openvino library is in /opt/intel/openvino/deployment_tools/inference_engine/lib/intel64/libcpu_extension_avx2.so.

This works fine on Ubuntu 16.04:
python app.py --enable_detection -m_ss /home/anu/drone/tellooo/extension/IR/FP32/MobileNetSSD_deploy.xml -l /opt/intel/openvino/deployment_tools/inference_engine/lib/intel64/libcpu_extension_avx2.so

**Comment by kodamap** [comment]
I appreciate your useful comment. I only tested this code with Windows10....

I added this in the `Readme`.
